#!/usr/bin/env bash
set -euo pipefail

show_help() {
  cat <<EOF
Usage:
  bash cmr_multi_task1/scripts/predict.sh <view> <split> [extra args]

view:  sax | 2ch | 4ch
split: val  -> predict held-out validation (imagesTs)
       test -> predict Codabench test set (test_images/<view>)

Examples:
  FOLDS="0"            bash cmr_multi_task1/scripts/predict.sh sax val
  FOLDS="0 1 2 3 4"    bash cmr_multi_task1/scripts/predict.sh 4ch test
  MAE=1                use MAE result dir + PretrainedTrainer plans

Environment overrides:
  GPU          CUDA_VISIBLE_DEVICES (default 0)
  FOLDS        space separated fold ids (default "0")
  CONFIGURATION 3d_fullres (default)
  TRAINER      nnUNetTrainer (default; ignored when MAE=1)
  RESULT_DIR   output directory (default auto)
  MAE=1        predict from MAE fine-tuned checkpoints
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then show_help; exit 0; fi
if [[ $# -lt 2 ]]; then echo "ERROR: view and split required"; show_help; exit 1; fi

source "$(dirname "${BASH_SOURCE[0]}")/env.sh"
if [[ "${MAE:-0}" == "1" ]]; then source "$(dirname "${BASH_SOURCE[0]}")/env_mae.sh"; fi

VIEW="${1,,}"; SPLIT="${2,,}"; shift 2 || true
DATASET_ID="$(cine_dataset_id "${VIEW}")"
if [[ -z "${DATASET_ID}" ]]; then echo "ERROR: unknown view '${VIEW}'"; exit 1; fi

GPU="${GPU:-0}"
FOLDS="${FOLDS:-0}"
CONFIGURATION="${CONFIGURATION:-3d_fullres}"
TRAINER="${TRAINER:-nnUNetTrainer}"

# Resolve input image directory.
case "${SPLIT}" in
  val)
    INPUT_DIR="${nnUNet_raw}/Dataset${DATASET_ID}_*/imagesTs" ;;
  test)
    INPUT_DIR="${TASK1_DATASET_ROOT}/test_images/${VIEW}" ;;
  *)
    echo "ERROR: split must be val or test"; exit 1 ;;
esac

# Expand glob to a real directory.
INPUT_DIR="$(ls -d ${INPUT_DIR} 2>/dev/null | head -n 1)"
if [[ -z "${INPUT_DIR}" || ! -d "${INPUT_DIR}" ]]; then
  echo "ERROR: input image dir not found for view=${VIEW} split=${SPLIT}"; exit 1
fi

# Build result dir.
TAG="plain"; [[ "${MAE:-0}" == "1" ]] && TAG="mae"
RESULT_DIR="${RESULT_DIR:-${TASK1_DATASET_ROOT}/predictions/${VIEW}_${SPLIT}_${TAG}}"
mkdir -p "${RESULT_DIR}"

# Find checkpoint dir.
DS_NAME="$(ls -d ${nnUNet_results}/Dataset${DATASET_ID}_* 2>/dev/null | head -n 1)"
if [[ -z "${DS_NAME}" ]]; then echo "ERROR: no result dir for Dataset${DATASET_ID} under ${nnUNet_results}"; exit 1; fi

FOLD_LIST=(${FOLDS})
if [[ "${#FOLD_LIST[@]}" -gt 1 ]]; then
  FOLD_ARG="all"
  ENSEMBLE_DIR="${RESULT_DIR}"
  # nnU-Net ensemble requires npz files saved during training.
  for f in "${FOLD_LIST[@]}"; do :; done
else
  FOLD_ARG="${FOLD_LIST[0]}"
  ENSEMBLE_DIR="${RESULT_DIR}"
fi

TRAINER_DIR="${TRAINER}"
PLAN_NAME="nnUNetPlans"
if [[ "${MAE:-0}" == "1" ]]; then
  TRAINER_DIR="PretrainedTrainer"
  # pick the MAE plans generated by preprocess_cine_mae_pretrained.sh
  PLAN_NAME="$(find "${nnUNet_preprocessed}/Dataset${DATASET_ID}_*" -maxdepth 1 -name "ptPlans__${MAE_PRETRAINING_NAME}*.json" -printf '%f\n' 2>/dev/null | sort | tail -n 1)"
  PLAN_NAME="${PLAN_NAME%.json}"
  if [[ -z "${PLAN_NAME}" ]]; then echo "ERROR: no MAE plans found. Run preprocess_cine_mae_pretrained.sh first."; exit 1; fi
fi

CMD=(nnUNetv2_predict)
if [[ "${FOLD_ARG}" == "all" ]]; then CMD+=(--disable_tta); fi
CMD+=(
  -i "${INPUT_DIR}" -o "${ENSEMBLE_DIR}"
  -d "${DATASET_ID}" -c "${CONFIGURATION}"
  -f "${FOLDS}"
)
if [[ "${MAE:-0}" == "1" ]]; then
  CMD+=(-tr "${TRAINER_DIR}" -p "${PLAN_NAME}")
else
  CMD+=(-tr "${TRAINER_DIR}" -p "${PLAN_NAME}")
fi
CMD+=("$@")

echo "[predict] view=${VIEW} split=${SPLIT} folds=${FOLDS} trainer=${TRAINER_DIR} plan=${PLAN_NAME}"
echo "  input  = ${INPUT_DIR}"
echo "  output = ${RESULT_DIR}"
CUDA_VISIBLE_DEVICES="${GPU}" "${CMD[@]}"

